# Generated by Django 4.2.7 on 2025-05-08 07:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical_system', '0003_alter_user_managers_remove_user_username_user_inn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=100)),
                ('experience', models.IntegerField(blank=True, help_text='Опыт работы в годах', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)])),
                ('description', models.TextField(blank=True, help_text='Дополнительная информация о враче', null=True)),
                ('photo', models.ImageField(blank=True, help_text='Фотография врача', null=True, upload_to='doctor_photos/')),
                ('education', models.TextField(blank=True, help_text='Образование и квалификация', null=True)),
                ('achievements', models.TextField(blank=True, help_text='Достижения и награды', null=True)),
                ('consultation_price', models.DecimalField(blank=True, decimal_places=2, help_text='Стоимость консультации', max_digits=10, null=True)),
                ('available_for_online', models.BooleanField(default=False, help_text='Доступен для онлайн-консультаций')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
            },
        ),
    ]
