# Generated by Django 4.2.7 on 2025-05-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_system', '0004_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='status',
            field=models.CharField(choices=[('PENDING', 'В обработке'), ('READY', 'Готов'), ('CANCELED', 'Отменен')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='result_file',
            field=models.FileField(blank=True, null=True, upload_to='analyses/'),
        ),
    ]
