# Generated by Django 4.2.7 on 2025-05-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_system', '0005_analysis_date_completed_analysis_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(choices=[('THERAPIST', 'Терапевт'), ('SURGEON', 'Хирург'), ('PEDIATRICIAN', 'Педиатр'), ('NEUROLOGIST', 'Невролог'), ('CARDIOLOGIST', 'Кардиолог'), ('DENTIST', 'Стоматолог')], max_length=100),
        ),
    ]
