# Generated by Django 4.2.7 on 2025-05-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_system', '0006_alter_doctor_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='analysis_file',
            field=models.FileField(blank=True, null=True, upload_to='medical_records/'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='complaints',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='status',
            field=models.CharField(choices=[('PENDING', 'В обработке'), ('READY', 'Готов')], default='PENDING', max_length=20),
        ),
    ]
