# Generated by Django 4.2.7 on 2025-05-27 00:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical_system', '0008_user_average_rating_visit_doctorrating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorrating',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='doctorrating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='doctorrating',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='medical_system.appointment'),
        ),
        migrations.AlterField(
            model_name='doctorrating',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctorrating',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctorrating',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterUniqueTogether(
            name='doctorrating',
            unique_together={('patient', 'appointment')},
        ),
        migrations.RemoveField(
            model_name='doctorrating',
            name='visit',
        ),
    ]
